# Generated by Django 5.1.3 on 2024-11-19 10:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chapter', '0001_initial'),
        ('comment', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='chapter',
            field=models.ForeignKey(default=7, on_delete=django.db.models.deletion.CASCADE, related_name='chapter_story', to='chapter.chapter'),
            preserve_default=False,
        ),
    ]
